server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Frontend URL and CORS
app.frontend.base-url=${APP_FRONTEND_BASE_URL:http://localhost:5173}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:${app.frontend.base-url}}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=venkatshivanuvvula@gmail.com
spring.mail.password=ymwn ikoz sduc cncy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true